---
default_install_hook_types: [pre-commit, pre-push, commit-msg]
repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v2.3.0
   hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
 - repo: https://github.com/astral-sh/ruff-pre-commit
   rev: v0.0.283
   hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
 - repo: local
   hooks:
    - id: run_tests
      name: pytests
      language: system
      pass_filenames: false
      always_run: true
      types: [python]
      entry: bash -c 'make test'
      stages: [push]
    - id: lint_&_format
      name: lint_format
      language: system
      types: [python]
      entry: bash -c 'make lint'
      stages: [push]
