version: '3.4'

services:
  postgres_db:
    image: postgres:15.3-bookworm
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: pwd_1234
      POSTGRES_DB: url_shortener
    ports:
        - "5432:5432"
  cache:
    image: redis/redis-stack:latest
    restart: no
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_ARGS: "--requirepass pwd_redis_1234"
