version: '3.4'

services:
  postgres_db_test:
    image: postgres:15.3-bookworm
    restart: no
    environment:
      POSTGRES_USER: test_dev_user
      POSTGRES_PASSWORD: test_pwd_1234
      POSTGRES_DB: test_url_shortener
    ports:
        - "5430:5432"
  cache:
    image: redis/redis-stack:latest
    restart: no
    ports:
      - "6370:6379"
    environment:
      REDIS_ARGS: "--requirepass pwd_test_redis_1234"
